version: '3.4'

services:
  onerostersync.net:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT=44312
    ports:
      - "61007:80"
      #- "44312:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro